
INSERT INTO `luxuryshop`.`admin` (`AID`, `ANAME`, `PSWD`) VALUES ('1', 'a', '123456');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (2, 1, 'a', 10.00, 20, '首饰', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (3, 1, 'b', 10.00, 20, '首饰', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '蓝红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (4, 1, 'ca', 10.00, 20, '首饰', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (5, 1, 'd', 10.00, 20, '首饰', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (6, 1, 'e', 10.00, 20, '首饰', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (7, 1, 'f', 10.00, 20, '皮包', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (8, 1, 'g', 10.00, 20, '皮包', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (9, 1, 'h', 10.00, 20, '皮包', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (10, 1, 'i', 10.00, 20, '皮包', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (11, 1, 'j', 10.00, 20, '装饰', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (12, 1, 'k', 10.00, 20, '装饰', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (13, 1, 'l', 10.00, 20, '装饰', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (14, 1, 'm', 10.00, 20, '装饰', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (15, 1, 'n', 10.00, 20, '装饰', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (16, 1, 'o', 10.00, 20, '装饰', 'ok', 'client/product/image/product-1.jpg', 10, 133, '100×150×200', 13.00, '红，蓝，棕');
