INSERT INTO `luxuryshop`.`admin` (`AID`, `ANAME`, `PSWD`) VALUES ('1', 'a', '123456');
# 配饰
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (1, 1, 'PREMIÈRE VELOURS腕表', 71800.00, 20, '配饰', '2020-06-12', 'PREMIÈRE 腕表的八角形轮廓与巴黎芳登广场的形状如出一辙。这一隽永恒久、堪称完美设计典范的建筑与腕表柔美妩媚的特质相互呼应。', 'client/product/image/peishi/1/peishi-1.jpg', 0, 133, '19.7 x 15.2 x 7.5毫米', 50.00, '黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (2, 1, 'PREMIÈRE JS4腕表', 36300.00, 20, '配饰', '2020-06-12', '表冠:表冠镶嵌蛋面切割缟玛瑙；表带:精钢与黑色皮革交织而成的链带；PREMIÈRE 腕表的八角形轮廓与巴黎芳登广场的形状如出一辙。这一隽永恒久、堪称完美设计典范的建筑与腕表柔美妩媚的特质相互呼应。', 'client/product/image/peishi/2/peishi-2.jpg', 0, 926, '26.1 x 20 x 7毫米', 50.6, '黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (3, 1, 'Lorenz Bäumer戒指', 34300, 20, '配饰', '2020-06-13', '精致款，白18K金，镶嵌中央主钻，黑色陶瓷；黑与白构成强烈反差，赋予ULTRA高级珠宝系列独一无二的韵味。这一系列完全采用香奈儿标志性的陶瓷材质制作，以纯粹的对比令人留下深刻印象。', 'client/product/image/peishi/3/peishi-3.jpg', 0, 133, '12.1 x 3 x 7毫米', 5.1, '蓝红，蓝，棕');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (4, 1, 'CAMÉLIA SCULPTÉ系列耳环', 25800, 20, '配饰', '2020-06-14', '材质: 白18K金，白色陶瓷，钻石；黑与白构成强烈反差，赋予ULTRA高级珠宝系列独一无二的韵味。这一系列完全采用香奈儿标志性的陶瓷材质制作，以纯粹的对比令人留下深刻印象。', 'client/product/image/peishi/4/peishi-4.jpg', 10, 133, '12.1 x 6毫米', 5.2, '黑宝石，钻石，铂金');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (5, 1, 'MONSIEUR腕表', 56000, 20, '配饰', '2020-06-15', '表带:黑色短吻鳄鱼皮纹小牛皮表带，白18K金三重折叠式表扣；白18K金表壳，饰边和表耳镶嵌66颗长阶梯形切割钻石（共计约重3.02克拉）', 'client/product/image/peishi/5/peishi-5.jpg', 0, 133, '40毫米', 59.0, '黑，白');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (6, 1, 'J12腕表', 49800, 20, '配饰', '2020-06-16', '现代制表典范J12腕表如今搭载Caliber 12.1机芯，它的传奇经久不衰，同时不断演绎创新。', 'client/product/image/peishi/6/peishi-6.jpg', 0, 133, '38 x 12.6毫米', 68.0, '黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (7, 1, 'COCO CRUSHJ11191耳环', 48200, 20, '配饰', '2020-06-17', '菱格纹，香奈儿品牌的标志性图案，在这个新系列展现极富视觉效果的摩登姿态；耳环可佩戴于耳垂上，也可拆下背面部件，佩戴于耳廓上方', 'client/product/image/peishi/7/peishi-7.jpg', 0, 133, '38 x 60毫米', 52.0, '金，银白');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (8, 1, 'PÉTALES DE CAMÉLIA J11667耳夹', 61200, 20, '配饰', '2020-06-18', '山茶花深受嘉柏丽尔•香奈儿钟爱，也为她的时装设计提供源源不断的灵感。', 'client/product/image/peishi/8/peishi-8.jpg', 0, 133, '38 x 60毫米', 62.0, '金，钻石白');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (9, 1, 'PÉTALES DE CAMÉLIA J11988耳夹', 126100, 20, '配饰', '2020-06-19', '羽毛是香奈儿女士于1932年创作的首个高级珠宝系列的主题之一，是品牌的重要象征符号。夹式耳环，采用可拆卸针式设计，有无耳洞均可佩戴', 'client/product/image/peishi/9/peishi-9.jpg', 10, 133, '120.2 x 60毫米', 90.0, '钻石白');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (10, 1, 'PLUME DE CHANEL J10815系列项链', 90600, 20, '配饰', '2020-06-20', '羽毛是香奈儿女士于1932年创作的首个高级珠宝系列的主题之一，是品牌的重要象征符号。', 'client/product/image/peishi/10/peishi-10.jpg', 0, 133, '120.2 x 60毫米', 102.0, '钻石白');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (11, 1, 'MADEMOISELLE PRIVÉ H2928腕表', 227800, 20, '配饰', '2020-06-21', 'Mademoiselle Privé系列向所有专业手工艺技术致敬，凝聚手工匠的精湛技艺，超凡卓越，精致迷人；黑色缎面表带，白18K金扣针式表扣镶嵌80颗钻石（约重0.49克拉）', 'client/product/image/peishi/11/peishi-11.jpg', 0, 133, '100×150×200', 102.0, '钻石白，黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (12, 1, 'COCO CRUSH J11786戒指', 25300, 20, '配饰', '2020-06-12', '菱格纹，香奈儿品牌的标志性图案，在这个新系列展现极富视觉效果的摩登姿态。', 'client/product/image/peishi/12/peishi-12.jpg', 0, 133, '20.1 x 1.2毫米', 3.22, '黄金色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (13, 1, 'COCO CRUSH J11874耳环', 35100, 20, '配饰', '2020-06-13', '白18K金，BEIGE米色18K金，钻石，菱格纹，香奈儿品牌的标志性图案，在这个新系列展现极富视觉效果的摩登姿态。', 'client/product/image/peishi/13/peishi-13.jpg', 0, 133, '40.1 x 1.2毫米', 13.00, '金色，银色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (14, 1, 'EXTRAIT DE CAMÉLIA手镯', 31800, 20, '配饰', '2020-06-14', '山茶花深受嘉柏丽尔•香奈儿钟爱，也为她的时装设计提供源源不断的灵感。', 'client/product/image/peishi/14/peishi-14.jpg', 0, 133, '40.1 x 1.2毫米', 15.2, '玫瑰金，钻石');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (15, 1, 'BOUTON DE CAMÉLIA戒指', 284100, 20, '配饰', '2020-06-15', '山茶花深受嘉柏丽尔•香奈儿钟爱，也为她的时装设计提供源源不断的灵感。', 'client/product/image/peishi/15/peishi-15.jpg', 0, 133, '36.1 x 13.2毫米', 8.20, '钻石');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (16, 1, 'IMPRESSION DE CAMÉLIA系列手镯', 191800, 20, '配饰', '2020-06-16', '山茶花深受嘉柏丽尔•香奈儿钟爱，也为她的时装设计提供源源不断的灵感。', 'client/product/image/peishi/16/peishi-16.jpg', 0, 133, '133.1 x 20.2毫米', 50.00, '黄金');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (17, 1, 'IMPRESSION DE CAMÉLIA系列手镯2', 71800, 20, '配饰', '2020-06-16', '山茶花深受嘉柏丽尔•香奈儿钟爱，也为她的时装设计提供源源不断的灵感。', 'client/product/image/peishi/17/peishi-17.jpg', 0, 133, '122.1 x 19.2毫米', 66.70, '钻石，黄金');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (18, 1, 'BOUTON DE CAMÉLIA系列胸针', 118500, 20, '配饰', '2020-06-16', '山茶花深受嘉柏丽尔•香奈儿钟爱，也为她的时装设计提供源源不断的灵感。', 'client/product/image/peishi/18/peishi-18.jpg', 0, 133, '19.1 x 20.2毫米', 10.2, '钻石');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (19, 1, 'IMPRESSION DE CAMÉLIA系列耳环', 44500, 20, '配饰', '2020-06-16', '山茶花深受嘉柏丽尔•香奈儿钟爱，也为她的时装设计提供源源不断的灵感。山茶花拥有接近几何正圆的花形，在艺术巧思的演绎下，或栩栩如生，或抽象写意，装点着鬓边、指间、前襟……', 'client/product/image/peishi/19/peishi-19.jpg', 10, 133, '123.1 x 20.2毫米', 31.10, '玫瑰金');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (20, 1, 'IMPRESSION DE CAMÉLIA系列耳环2', 331000, 20, '配饰', '2020-06-16', '山茶花深受嘉柏丽尔•香奈儿钟爱，也为她的时装设计提供源源不断的灵感。', 'client/product/image/peishi/20/peishi-20.jpg', 0, 133, '133.1 x 20.2毫米', 28.00, '钻石，黄金');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (21, 1, 'Lace 「蕾丝」', 2260, 20, '配饰', '2020-06-16', '设计灵感源自延龄草，独特的三叶形态分别代表了纯洁、美丽及健康的美好祝愿。启发自印度奥里萨（Orissa）的镂空工艺，应用于铂金 Lace 戒指之上，以蕾丝图案代替叶纹，呈现优雅的女性美。', 'client/product/image/peishi/21/peishi-21.jpg', 0, 133, '15圈度', 4.00, '钻石，铂金');

# 服饰
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (101, 1, 'DRESS WITH BUTTON-DOWN COLLAR',   31000, 20, '服饰', '2020-06-16', 'Multicolor Tie & Dior Cotton', 'client/product/image/fushi/cloth-1.jpg', 0, 133, 'XM-XL-XML', 9999, '黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (102, 1, 'DIORAURA LONG DRESS',             42000, 20, '服饰', '2020-06-16', 'Blue Tie & Dior Wax Cotton with Laces', 'client/product/image/fushi/cloth-2.jpg', 0, 133, 'XM-XL-XML', 9999, '橘色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (103, 1, 'CROPPED SKIRT',                   39800, 20, '服饰', '2020-06-16', 'Blue Denim', 'client/product/image/fushi/cloth-3.jpg', 0, 133, 'XM-XL-XML', 9999, '黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (104, 1, 'JACKET',                          12900, 20, '服饰', '2020-06-16', 'Black Fishnet with Floral Pattern', 'client/product/image/fushi/cloth-4.jpg', 0, 133, 'XM-XL-XML', 9999, '黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (105, 1, 'BOMBER JACKET',                   52000, 20, '服饰', '2020-06-16', '经典针织服饰融入精致细节和品牌标志性元素后焕发新的活力。这款开衫采用深蓝色针织羊毛混纺材质，口袋上别具匠心地融入经典红绿织带细节，亮金色调双G标识彰显高雅不俗的时尚品味。', 'client/product/image/fushi/cloth-5.jpg', 0, 133, 'XM-XL-XML', 9999, '军绿');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (106, 1, 'BAR JACKET',                      37400, 20, '服饰', '2020-06-16', '这款牛仔裤采用经特殊石磨漂白处理的出众材质，呈现出大理石纹做旧效果，搭配经典五袋设计和直筒版型。最新系列在牛仔布这一备受追捧的经典材质上大放异彩，运用多种不同造型和处理工艺为其注入全新活力。', 'client/product/image/fushi/cloth-6.jpg', 0, 133, 'XM-XL-XML', 9999, '海军蓝');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (107, 1, 'DIORAURA ROMPER',                 24900, 20, '服饰', '2020-06-16', '在最新系列中，Gucci在牛仔布这一备受追捧的经典材质上大放异彩，运用多种不同造型和处理工艺为其注入全新活力。这款夹克由深蓝色牛仔布制作而成，采用方形剪裁，七分袖为其增添别样韵味。该设计从星座世界中汲取灵感，金色金属纽扣巧妙融入让人联想到半人马座的细节元素。', 'client/product/image/fushi/cloth-7.jpg', 0, 133, 'XM-XL-XML', 9999, '橙黄色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (108, 1, 'PANTS',                           8400, 20, '服饰', '2020-06-16', '2020早秋推出全新的配饰和成衣系列，采用可回收利用的材料和辅料制作，以此践行品牌对可持续性发展的一贯承诺。Gucci Off The Grid系列是Gucci Circular Lines的首个系列，该产品线的设计初衷是支持品牌大力发展循环生产的企业愿景。秉持环保这一设计理念，Gucci Off The Grid系列充分运用各种可回收利用和可持续采购的有机生物基材料。再生尼龙由可回收利用的缝纫线和辅料制成，依托亮橘色不透明背景突显品牌独具一格的GG图案元素。', 'client/product/image/fushi/cloth-8.jpg', 0, 133, '133.1 x 20.2毫米', 9999, '黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (109, 1, 'LARGE JEANS',                     7700, 20, '服饰', '2020-06-16', 'Navy Blue Wool and Silk', 'client/product/image/fushi/cloth-9.jpg', 0, 133, 'XM-XL-XML', 9999, '黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (110, 1, 'BLOUSE',                          11200, 20, '服饰', '2020-06-16', 'Multicolor Silk', 'client/product/image/fushi/cloth-10.jpg', 0, 133, 'XM-XL-XML', 9999, '黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (111, 1, '饰织带针织羊毛混纺开衫',            14500, 20, '服饰', '2020-06-16', 'Black Wool and Silk', 'client/product/image/fushi/cloth-11.jpg', 0, 133, 'XM-XL-XML', 9999, '黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (112, 1, '石磨漂白常规版型牛仔裤',            4900, 20, '服饰', '2020-06-16', 'Black Washed Denim', 'client/product/image/fushi/cloth-12.jpg', 0, 133, 'XM-XL-XML', 9999, '牛仔色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (113, 1, '石磨水洗牛仔夹克',                 13400, 20, '服饰', '2020-06-16', 'Green and Black Camouflage Technical Cotton', 'client/product/image/fushi/cloth-13.jpg', 0, 133, 'XM-XL-XML', 9999, '浅蓝');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (114, 1, 'Gucci Off The Grid系列兜帽',       12600, 20, '服饰', '2020-06-16', 'Blue Denim', 'client/product/image/fushi/cloth-14.jpg', 0, 133, 'XM-XL-XML', 9999, '橘');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (115, 1, '饰Gucci字样人造丝棉混纺夹克',       13900, 20, '服饰', '2020-06-16', '风靡设计融合全新的紧身造型和流线型美学理念，透过Gucci别致的美学视角焕发新的活力。这款飞行员夹克采用绿色日晒效果棉人造丝硬缎混纺材质，搭配短款紧身廓形，贯穿整个衣身的超大条纹缔造点睛之笔。对比色Gucci字样刺绣充满复古气息，演绎老式广告的经典魅力。', 'client/product/image/fushi/cloth-15.jpg', 0, 133, 'XM-XL-XML', 9999, '绿');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (116, 1, '针织棉短裤',                       7500, 20, '服饰', '2020-06-16', '这款短裤两侧饰有互扣式双G条纹，这一别致装饰贯穿于Gucci最新系列。侧边饰带为Gucci经典标识融入运动活力，唤起人们对于复古运动装常见品牌标识饰带的回忆。', 'client/product/image/fushi/cloth-16.jpg', 0, 133, 'XM-XL-XML', 9999, '空军绿');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (117, 1, '饰Gucci标签羊毛夹克',              17600, 20, '服饰', '2020-06-16', '缝制夹克运用革新的美学理念进行重新演绎，在经典设计中注入现代精髓，成为融合精致面料和热门休闲材质的混搭造型的主打单品。这款夹克采用传统设计，由蓝色棉布制作而成，可与配套的背心和牛仔裤演绎出众造型，颠覆传统剪裁风格。', 'client/product/image/fushi/cloth-17.jpg', 0, 133, 'XM-XL-XML', 9999, '黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (118, 1, '饰Gucci标签补丁效果牛仔夹克',       18500, 20, '服饰', '2020-06-16', '2020春夏系列深入探索了牛仔布这一经典材质，运用多种不同造型和处理赋予该面料新的活力。这款牛仔夹克使用多种工艺进行特殊水洗处理后，呈现出做旧补丁效果，尽显复古风情。胸口处巧妙融入法语格言“Gucci quelle qu’en soit la saison”刺绣标签。该格言的意思是“Gucci服饰四季皆宜”，充分诠释了Gucci服饰可自由穿搭的设计理念。', 'client/product/image/fushi/cloth-18.jpg', 0, 133, 'XM-XL-XML', 9999, '牛仔蓝');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (119, 1, '刺绣绳绒卫衣',                     8300, 20, '服饰', '2020-06-16', '这款黑色绳绒卫衣采用已经成为品牌标志的浪漫箴言，正面饰有 Gucci、“Maison de LAmour”和“Sine Amore Nihil”刺绣，短袖设计，装饰同色醋酸纤维饰边。灵感源自运动装和休闲装的风格元素相互交织，以精致柔软的面料呈现动感造型，演绎 Gucci 经典风格', 'client/product/image/fushi/cloth-19.jpg', 0, 133, 'XM-XL-XML', 9999, '黑');

#香水
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (200, 1, '璀璨香水',    1530, 20, '香氛', '2020-06-16', '全新迪奥JOY璀璨香水*，愉悦芳息迸发而出，尽绽繁花千面魅力。柑橘香气清新闪耀，与绚丽玫瑰和明亮茉莉携舞，醇柔檀香木气息温暖拥覆，交织一缕香草芬芳，绽放活泼笑意。', 'client/product/image/xiangshui/xiangshui-1.jpg', 0, 133, '50ml', 50, '无色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (201, 1, '香氛皂',      260, 20, '香氛', '2020-06-16', '玲珑小巧的沐浴香氛皂，仿佛手心珍宝。洁白绵密的泡沫，细腻柔滑，轻覆肌肤，芬芳萦绕。悦享沐浴时光，快乐由心而生。', 'client/product/image/xiangshui/xiangshui-2.jpg', 0, 133, '6×6', 100, '无色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (202, 1, '沐浴露',      430, 20, '香氛', '2020-06-16', 'JOY by Dior 沐浴露*，质地柔滑细腻，泡沫丰盈绵密。 芬芳柔覆，萦绕肌肤，愉悦感官，延续JOY by Dior香水**的曼妙芳迹。', 'client/product/image/xiangshui/xiangshui-3.jpg', 0, 133, '200ml', 200, '无色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (203, 1, '随行淡香氛',  385, 20, '香氛', '2020-06-16', '随行淡香氛	真我随行淡香氛，精美珠宝般玲珑瓶身，置于手袋小巧轻盈。柔润圆珠轻掠过颈部与手腕，触肤留存真我繁花馨香。精准取用：瓶身顶端圆珠精准控制香氛取用量，留香无痕。丝般触感：质地奢柔而轻盈，感性而清新。灵动随行：20毫升装小巧轻盈，精细螺旋盖密封瓶身，滴香不落。真我随行淡香氛，明媚芬芳萃自璀璨繁花：愉悦前调迸发而出，血橙气息唤醒感官。苦橙花香于中调明媚闪耀，如地中海阳光般耀眼绚烂。大马士革玫瑰芬芳感性醇柔，传递触动感官的温暖馨香。', 'client/product/image/xiangshui/xiangshui-4.jpg', 0, 133, '20ml', 20, '无色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (204, 1, '香发喷雾',    585, 20, '香氛', '2020-06-16', '香发喷雾	感性花香，尽释真我女性魅力。轻盈迷人，优雅芬芳翩然萦绕。全新真我香发喷雾，玲珑细颈瓶身，随时、随地、随心延续真我芳迹。喷洒瞬息，曼妙花香随发丝浮动，悄然弥漫。 真我是由匠心技艺创作而成的一束馥郁繁花，致献迷人女性。', 'client/product/image/xiangshui/xiangshui-5.jpg', 0, 133, '40ml', 40, '无色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (205, 1, '倾世之金香氛', 1530, 20, '香氛', '2020-06-16', '倾世之金香氛高贵感性，是真我系列精髓之作。相互交织的茉莉纯香和五月玫瑰，来自于格拉斯Dior迪奥专属合作庄园，唤出香草晚香玉迷人的东方气息。繁花簇拥之中，浓郁的格拉斯大花茉莉绽放着果香气息，五月玫瑰掀起撩人的辛香味。', 'client/product/image/xiangshui/xiangshui-6.jpg', 0, 133, '40ml', 40, '无色');

#皮具
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (301, 1, 'ONTHEGO 手袋',       21000, 20, '皮具', '2020-06-16', 'Onthego 手袋在 Monogram Giant 帆布的衬托下醒目迷人，侧边与手柄点缀 Monogram Reverse 图案，相似风尚中窥见色彩与纹理的变化。大号构型内含充裕容量，搭配肩带与 Toron 手柄，日常生活随心出发。', 'client/product/image/piju/piju-1.jpg', 0, 133, '41.0 x 34.0 x 19.0 cm', 999, '乌木');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (302, 1, 'CLÉMENCE 钱夹',      6700, 20, '皮具', '2020-06-16', 'Clémence 钱夹碰撞 Monogram Empreinte 皮革，以 Monogram 花卉塑造拉链头，优雅跻身 Blooming Flowers 系列。纤薄构型内含考究设计，配有多个口袋和卡位。', 'client/product/image/piju/piju-2.jpg', 0, 133, '20.0 x 9.0 x 2.0 cm', 999, '蓝红');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (303, 1, 'SARAH 钱夹',         5500, 20, '皮具', '2020-06-16', '信封样式的 Sarah 钱夹将优雅动人的 Damier Azur 帆布外层与精心设计的内层结构结合，提供了多个内袋和信用卡卡槽。', 'client/product/image/piju/piju-3.jpg', 0, 133, '19.0 x 10.5 x 2.5 cm', 999, '乳白色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (304, 1, 'ZIPPY 拉链钱夹',     7300, 20, '皮具', '2020-06-16', 'Zippy 拉链钱夹取材经典 Monogram 帆布，以生动意趣展现吉祥物 Vivienne与巴黎埃菲尔铁塔之景，致意路易威登的旅行传承。', 'client/product/image/piju/piju-4.jpg', 0, 133, '19.5 x 10.5 x 2.5 cm', 999, '彩色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (305, 1, 'TWIST 中号手袋',     31500, 20, '皮具', '2020-06-16', '2020 年夏季，路易威登以绚丽色彩重绎品牌经典。本款 Twist 中号手袋取材深染 Epi 皮革，搭配有机玻璃手柄和炫彩名牌及挂饰，更有 LV Twist 扭锁传递标志性格调。可拆卸皮革肩带实现多种背携方式。', 'client/product/image/piju/piju-5.jpg', 0, 133, '23.0 x 17.0 x 9.5 cm', 999, '红色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (306, 1, 'TWIST 中号手袋2',    31500, 20, '皮具', '2020-06-16', '本款 Twist 中号手袋以慵懒格调诠释新古典主义设计。Epi 皮革手柄搭配刺绣缎面宽肩带，后者将路易威登标识与 Monogram 花卉分饰两侧，实现贴身斜挎方式。', 'client/product/image/piju/piju-6.jpg', 0, 133, '23.0 x 17.0 x 9.5 cm', 999, '深绿');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (307, 1, 'VANITY 小号手袋',    19800, 20, '皮具', '2020-06-16', '2020 春夏季见证 Nicolas Ghesquitère 为路易威登旅行传承谱写的当代乐章。本款都市手袋以 Monogram 和 Monogram Reverse 帆布重绎 Nice 化妆包，无论手提或系上皮革链条肩带实现肩背或斜挎，均可令柔软轻盈的设计随身而动。', 'client/product/image/piju/piju-7.jpg', 0, 133, '19.0 x 13.0 x 11.0 cm	', 999, '古典色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (308, 1, 'PETITE MALLE 手袋',  230000, 20, '皮具', '2020-06-16', '此款 Petite Malle 手袋于 2020 春夏系列时装秀上亮相，由华贵鳄鱼皮制成。多彩波点图案令人联想到花卉和动物元素，由路易威登工匠亲手打造，令每款手袋别具风情。品牌经典硬箱为灵感之源。', 'client/product/image/piju/piju-8.jpg', 0, 133, '20.0 x 12.5 x 5.0 cm', 999, '虎皮色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (309, 1, 'ONTHEGO 手袋',       25100, 20, '皮具', '2020-06-16', 'Onthego 手袋上演 Damier 与 Monogram 图案的妙趣交融，在水洗丹宁色调的渲染中令帆布呈现微妙的质感变化。Monogram 元素再添些许雅致，皮革饰边点亮醒目轮廓，充裕空间适宜日常背携。', 'client/product/image/piju/piju-9.jpg', 0, 133, '41.0 x 34.0 x 19.0 cm', 999, '黑色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (310, 1, 'PALM 中号双肩包',    17800, 20, '皮具', '2020-06-16', '在2016年早春系列时装展大放异彩的此款背包风格个性时尚。它延续了华丽的外形，于细节处体现出 LV 气质。', 'client/product/image/piju/piju-10.jpg', 0, 133, '30.0 x 33.0 x 16.0 cm', 999, '乌木色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (311, 1, 'ZIPPY XL 钱夹',      31000, 20, '皮具', '2020-06-16', '此款极为稀有的鸵鸟皮版Zippy XL钱夹集出众的实用性与奢华的时尚感于一身。足可与小包袋相媲美的充足容量，配有手柄，便于提携。', 'client/product/image/piju/piju-11.jpg', 0, 133, '23.0 x 15.0 x 4.0 cm', 999, '黑色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (312, 1, 'COIN 卡夹',          2800, 20, '皮具', '2020-06-16', 'Coin 卡夹以 Monogram Eclipse 涂层帆布和 Monogram Eclipse Reverse 涂层帆布呈现深浅交替，利落硬朗的剪裁囊括卡位、拉链零钱袋和钞票隔层，搭配 LV 字母拉链头。', 'client/product/image/piju/piju-12.jpg', 0, 133, '8.0 x 14.5 x 1.0 cm', 999, '黑色，浅蓝');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (313, 1, 'MULTIPLE 钱夹',      4600, 20, '皮具', '2020-06-16', 'Virgil Abloh 与日本街头服饰设计先锋 Nigo 联袂打造 Multiple 钱夹。背起 LV MADE 标识的乌龟图案栖身 Giant Damier Ebene 帆布之上，多卡位可收纳卡片、收据和钞票，亦可置于口袋。', 'client/product/image/piju/piju-13.jpg', 0, 133, '11.5 x 9.0 x 1.5 cm', 999, '乌木');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (314, 1, 'BRAZZA 钱夹',        6500, 20, '皮具', '2020-06-16', 'Brazza 钱夹选用 Damier Graphite 帆布，印有男装艺术总监 Virgil Abloh 设计的新款交织字母路易威登品牌标识。彩色标识为这款多功能钱夹增添玩趣。', 'client/product/image/piju/piju-14.jpg', 0, 133, '10.0 x 19.0 x 2.0 cm', 999, '灰黑色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (315, 1, 'SOFT TRUNK 手袋',    28200, 20, '皮具', '2020-06-16', 'Soft Trunk 手袋选用 Monogram Eclipse 帆布与雾黑色金属件，搭配可调节黑色皮革肩带，实现软质邮差包造型。加固边角缓缓道出品牌经典硬箱之韵，广口设计方便取放物品，柔软质地带来随身而动的背携体验', 'client/product/image/piju/piju-15.jpg', 0, 133, '25.0 x 18.0 x 10.0 cm', 999, '黑色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (316, 1, 'BESACE ZIPPÉE 手袋', 15800, 20, '皮具', '2020-06-16', 'Besace Zippée 中号手袋采用贴身设计，宽敞的内部空间可容纳文件或平板电脑。该版本由 Monogram Eclipse 帆布打造，属于 Gaston Labels 限量版系列，其压纹皮革贴饰借鉴了Gaston-Louis Vuitton 收藏的复古行李标签设计。', 'client/product/image/piju/piju-16.jpg', 0, 133, '35.0 x 26.5 x 13.0 cm', 999, '黑色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (317, 1, 'ALPHA 邮差包',       14600, 20, '皮具', '2020-06-16', 'Alpha 邮差包在路易威登经典 Damier Graphite 帆布与黑色金属件的构造中释放摩登气息，别致外袋与两只内袋令物品取放便捷有序，宽肩带成就舒适的斜挎体验。', 'client/product/image/piju/piju-17.jpg', 0, 133, '26.0 x 17.0 x 5.0 cm', 999, '灰黑');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (318, 1, 'CABAS 手袋',         23300, 20, '皮具', '2020-06-16', '由经典Monogram帆布和天然皮革制成，搭配男装艺术总监Virgil Abloh的标志性金色链条和安全别针，这款Cabas Voyage男士托特手袋内部空间充裕，可以容纳一台笔记本电脑、几份杂志和几本书。包内有一个拉链贴袋，可装iPad，以及两个可放手机的内贴袋。', 'client/product/image/piju/piju-18.jpg', 0, 133, '40.5 x 14.5 x 32.0 cm', 999, '木橙色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (319, 1, 'ANTON TOTE 手袋',    15800, 20, '皮具', '2020-06-16', '兼具优雅风格与商务气质，此款Anton Tote手袋于利落简约的外观设计之中暗藏多个实用口袋与隔层。配有手柄和可拆卸肩带，可手提，可肩背。', 'client/product/image/piju/piju-19.jpg', 0, 133, '34.0 x 37.0 x 7.0 cm', 999, '黑色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (320, 1, 'SOFT TRUNK 手袋2',   35000, 20, '皮具', '2020-06-16', '此款 Soft Trunk 邮差包由结实的优质塑料制成，表面印有标志性的 Monogram 图案，另配深色牛皮饰边。透明侧面设计可令内部构造一览无遗，并搭配内置双层口袋。可拆卸肩带，可调节，便于肩背。', 'client/product/image/piju/piju-20.jpg', 0, 133, '25.0 x 18.0 x 10.0 cm', 999, '暗橙色');
INSERT INTO `luxuryshop`.`luxury`(`LID`, `AID`, `LNAME`, `PRICE`, `RESTNUM`, `TYPE`, `DATE`, `INFOR`, `IMAGE`, `SALENUM`, `VIEWCOUNT`, `SIZE`, `WEIGHT`, `COLOR`) VALUES (321, 1, '马衔扣1955系列肩背包', 19000, 20, '皮具', '2020-06-16', 'Gucci 马衔扣1955系列手袋在2020早春系列中惊艳亮相，以全新视角演绎经典设计。这一手袋延用了六十余年前经典单品的线条与造型，将经典细节与现代精神巧妙融合，强调了马衔扣这一品牌标志性设计元素。灵感源自马术世界的双环和连接条两个元素构成的这一设计图案已经成为品牌最耀眼的标志性元素之一。', 'client/product/image/piju/piju-21.jpg', 0, 133, '25厘米（宽）x 18厘米（高）x 8厘米（深）', 840, '乌木色，米色');
